export default [
  {
    id: 1,
    title: "NEW TIER LIST for PATCH 13.10 - EVERYTHING HAS CHANGED!",
    pageName: "Skill Capped Challenger LoL Guides",
    views: "149K views • 1 day ago",
    thumbnail: "/imgs/Thumbnails/league.jpg",
    pageImg: "/imgs/Thumbnails/league-channel.jpg",
    official: true,
  },
  {
    id: 2,
    title: "علي قنديل:فين الدولة العربية الجميلة دي؟",
    pageName: "Ali Quandil",
    views: "36K views • 2 days ago",
    thumbnail: "/imgs/Thumbnails/aliquandil.jpg",
    pageImg: "/imgs/Thumbnails/aliquandil-channel.jpg",
    official: true,
  },
  {
    id: 3,
    title: "Front-end Projects | افكار مشاريع فرونت اند",
    pageName: "Codezilla",
    views: "99K views • 1 year ago",
    thumbnail: "/imgs/Thumbnails/codezilla.jpg",
    pageImg: "/imgs/Thumbnails/codezilla-channel.jpg",
    official: true,
  },
  {
    id: 4,
    title: "[Arabic]Learn JavaScript In One Video - Part One",
    pageName: "Elzero Web School",
    views: "105K views • 6 months ago",
    thumbnail: "/imgs/Thumbnails/elzero.jpg",
    pageImg: "/imgs/Thumbnails/elzero-channel.jpg",
    official: true,
  },
  {
    id: 5,
    title: "Solo Leveling | OFFICIAL TEASER",
    pageName: "Crunchyroll Collection",
    views: "4.5M views • 1 month ago",
    thumbnail: "/imgs/Thumbnails/soloLeveling.jpg",
    pageImg: "/imgs/Thumbnails/solo-channel.jpg",
    official: true,
  },
  {
    id: 6,
    title: "Create A Food Website Design Using | HTML & CSS",
    pageName: "WT Master Code",
    views: "62K views • 10 months ago",
    thumbnail: "/imgs/Thumbnails/site.jpg",
    pageImg: "/imgs/Thumbnails/site-channel.jpg",
    official: true,
  },
];
